blank_issues_enabled: false

contact_links:

  - name: PygameUI 
    url: https://github.com/djoezeke/pygameui
    about: Modern GUIs with pygame.

  - name: PygameUI Issues | Bug Bounty
    url: https://github.com/djoezeke/pygameui/issues
    about: Please report issues and vulnerabilities here.

  - name: PygameUI Releases
    url: https://github.com/djoezeke/pygameui/releases
    about: Please latest PygameUI release here.
